version: '3.1'

services:

  pugrat-server:
    image: ghcr.io/tylerwhardy/pugrat-server-image:latest
    container_name: pugrat-server
    restart: unless-stopped
    stdin_open: true      # keeps stdin open
    tty: true             # allocates a TTY
    ports:
      - "5555:5555"
    volumes:
      - ./data/screenshots:/app/images/screenshots
      - ./data/webcam:/app/images/webcam
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - pugrat

networks:
  pugrat:
    name: pugrat
