
name: CI – Build, Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  checks: write
  id-token: write
  actions: read

jobs:  # Build & Push Multi-arch Docker Images
  build-and-push:
    name: 🐋 Build & Push Docker Images (multi-arch)
    runs-on: ubuntu-latest
#    needs: [codeql, dependency-audit, unit-test, secret-scan]
    strategy:
      matrix:
        image:
          - name: pugrat-server-image
            context: pugrat-server-image
            dockerfile: server/Dockerfile
            tag: latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push ${{ matrix.image.name }} (multi-arch)
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.dockerfile }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:${{ matrix.image.tag }}
